CPU_THRESHOULD=80
RAM_THRESHOULD=85
DISK_THRESHOULD=90

SERVICES="ssh ufw fail2ban"

# Telegram
TG_BOT_TOKEN=""
TG_CHAT_ID=""

# Email
EMAIL_TO=""
EMAIL_FROM=""

LOG_FILE="/var/log/server-health.log"
HOSTNAME="$(hostname)"

DAEMON_INTERVAL=300
